kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control
  namespace: travel-control
  labels:
    kiali_wizard: request_routing
spec:
  hosts:
    - >-
      istio-ingressgateway-istio-system.apps.cluster-e16a.gcp.redhatworkshops.io
  gateways:
    - travel-control/control-gateway
  http:
    - route:
        - destination:
            host: control.travel-control.svc.cluster.local
            subset: v1
          weight: 100
