kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control-gateway
  namespace: travel-control
  labels:
    kiali_wizard: request_routing
spec:
  servers:
    - hosts:
        - >-
          istio-ingressgateway-istio-system.apps.cluster-e16a.gcp.redhatworkshops.io
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway