kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  namespace: travel-agency
  name: travels
  labels:
    kiali_wizard: traffic_shifting
  annotations: ~
spec:
  host: travels.travel-agency.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
