kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control-gateway
  namespace: travel-control
  labels:
    kiali_wizard: request_routing
spec:
  servers:
    - hosts:
        - >-
          istio-ingressgateway-istio-system-travel-agency.apps.cluster-8475r.8475r.sandbox1572.opentlc.com
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway